name: weather_app
description: "weather app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


flutter_native_splash:
  color: '#1B4D34'
  image: assets/images/kevych_solutions_logo_image.png


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  go_router: ^13.2.0
  flutter_native_splash: ^2.3.11
  json_serializable: ^6.7.1
  flutter_svg: ^2.0.10+1
  multiple_result: ^5.1.0
  freezed: ^2.4.7
  geolocator: ^11.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  

fonts:
  - family: SourceSans3
    fonts:
      - asset: assets/fonts/SourceSans3.ttf
 
 
